name: Bug Report
description: Report a reproducible defect
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide exact commands or a minimal repro.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: Tag, commit SHA, or branch
      placeholder: v0.1.0
  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: Paste relevant output (redacted)
      render: shell
