name: Good First Issue
description: Maintainer-friendly starter task with clear acceptance criteria
title: "good first issue: "
labels: ["good first issue"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Summary
      description: What should be built or improved?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List objective conditions to mark complete.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links to relevant files/docs for first-time contributors.
